// Simple script to display admin setup instructions

console.log('🚀 Bite&Co Admin Setup Instructions')
console.log('=====================================')
console.log('')
console.log('Default admin credentials have been configured:')
console.log('   Username: admin')
console.log('   Password: admin123')
console.log('   Email: admin@biteandco.com')
console.log('')
console.log('🔗 To access the admin dashboard:')
console.log('   1. Go to: http://localhost:3002/login')
console.log('   2. Enter the credentials above')
console.log('   3. You will be redirected to the dashboard')
console.log('')
console.log('✅ The admin user will be created automatically on first login!')
console.log('')
console.log('📱 The landing page is available at: http://localhost:3002')
console.log('🔒 The dashboard is protected and requires authentication')
console.log('')
console.log('🎉 Setup complete! You can now test the application.')
